name: Fatih Mehmet Özcan
title: Fatih Mehmet Özcan
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
url: https://fatihmeh.github.io
logo: /favicon.svg
social:
  links:
    - https://github.com/fatihmeh
    - https://gitlab.com/fatihmehmetozcan
collections:
  notes:
    output: true